app/main/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2018/8/29 17:52
# @Author  : geekspeng
# @Email   : geekspeng@icloud.com
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField
from wtforms.validators import DataRequired, ValidationError


class ConvertBookForm(FlaskForm):
    convert_from = SelectField('Convert from', validators=[DataRequired()], coerce=str)
    convert_to = SelectField('Convert to', validators=[DataRequired()], coerce=str)
    submit = SubmitField('Convert Book')

    def __init__(self, book, *args, **kwargs):
        super(ConvertBookForm, self).__init__(*args, **kwargs)
        self.convert_from.choices = [(data.format.lower(), data.format.lower()) for data in book.data]
        self.convert_to.choices = [('azw3', 'azw3'), ('mobi', 'mobi'), ('epub', 'epub'), ('fb2', 'fb2'), ('pdf', 'pdf'),
                                   ('docx', 'docx'), ('txt', 'txt')]

    def validate_convert_to(self, field):
        if self.convert_from.data == field.data:
            raise ValidationError('Book format cannot be the same')

app/main/__init__.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/7
# @Author  : geekspeng
# @Email   : geekspeng@icloud.com
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/7
# @Author  : geekspeng
# @Email   : geekspeng@icloud.com
import os
from shutil import move

from flask import render_template, url_for, redirect, request, flash, current_app, send_from_directory
from flask_login import login_required, current_user
from flask_uploads import extension
from markupsafe import Markup

from app import uploads
from app.main import main
from app.main.forms import ConvertBookForm
from app.models.books import Books, Data
from app.utils import book_format, helper
from app.utils.email import send_book


@main.route("/", defaults={'page': 1})
@main.route('/page/<int:page>')
@login_required
def index(page):
    pagination = Books.get_books_pagination(page=page, per_page=current_app.config['BOOKS_PER_PAGE'], db_filter=True,
                                            order=Books.timestamp.desc())
    books = pagination.items
    return render_template('main/index.html', books=books, pagination=pagination, title="Home")


@main.route("/search", methods=["GET"])
@login_required
def search():
    term = request.args.get("query").strip().lower()
    books = []
    if term:
        books = Books.search_book(term)
    return render_template('main/index.html', books=books, pagination=None, title="Results")


@main.route("/upload", methods=["POST"])
@login_required
def upload():
    for file in request.files.getlist('btn-upload'):
        if not uploads.extension_allowed(extension(file.filename)):
            flash(Markup('File extension "%s" is not allowed to be uploaded to this server' % extension(file.filename)),
                  "warning")
            return redirect(url_for('main.index'))

        # save file
        file_name, file_extension = os.path.splitext(file.filename)
        folder = os.path.join(current_user.email, file_name)
        file_path = helper.resolve_folder_conflict(current_app.config['UPLOAD_FOLDER'], folder)
        saved_file_name = uploads.save(file, folder=file_path, name=file.filename)

        # get book meta
        meta = book_format.process(uploads.path(saved_file_name), file_path, file_name, file_extension[1:])

        # move file
        if meta.title != meta.file_name:
            new_file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_path,
                                         meta.title + file_extension)
            move(uploads.path(saved_file_name), new_file_path)
            if meta.cover_path:
                new_cover_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_path,
                                              meta.title + '.jpg')
                move(meta.cover_path, new_cover_path)

        # add book
        Books.add_book(meta)
    flash(Markup('File upload completed.'), "info")
    return redirect(url_for('main.index'))


@main.route("/delete/<int:book_id>/")
@login_required
def delete_book(book_id):
    Books.delete_book(book_id)
    flash(Markup('Book successfully deleted'), "info")
    return redirect(url_for('main.index'))


@main.route('/send/<int:book_id>')
@login_required
def send_to_kindle(book_id):
    if current_user.kindle_email:
        book = Books.query.get_or_404(book_id)
        res = send_book(current_user, book)
        if res:
            flash(Markup(res), "warning")
        else:
            flash(Markup("Book successfully queued for sending to %s" % current_user.kindle_mail), "success")
    else:
        flash(Markup("Please configure your kindle e-mail address first..."), "error")
        return redirect(url_for('auth.change_kindle_email'))
    return redirect(url_for('main.index'))


@main.route("/book/convert/<int:book_id>", methods=['GET', 'POST'])
@login_required
def convert_book(book_id):
    book = Books.query.get_or_404(book_id)
    form = ConvertBookForm(book)
    if form.validate_on_submit():
        book_format_from = form.convert_from.data
        book_format_to = form.convert_to.data
        if current_app.config['CONVERT_TOOL_PATH'] is None:
            flash(Markup("ebook-converter failed, there is no conversion tool"), "success")
            return redirect(url_for('main.index'))
        result = Books.convert_book_format(book_id, current_app.config['CONVERT_TOOL_PATH'], book_format_from.upper(),
                                           book_format_to.upper())
        if result is None:
            flash(Markup("Book successfully converted"), "success")
            return redirect(url_for('main.index'))
        else:
            flash(Markup("There was an error converting this book: %s" % result), "error")
    return render_template('main/convert_book.html', title='Convert Book', book=book, form=form)


@main.route("/read/<file_format>/<int:book_id>")
@login_required
def read_book(file_format, book_id):
    book = Books.query.get_or_404(book_id)
    file_name = book.title + '.' + file_format.lower()
    if file_format.lower() == "pdf":
        return render_template('main/readpdf.html', book_id=book_id, file_name=file_name)
    elif file_format.lower() == "txt":
        return render_template('main/readtxt.html', book_id=book_id, file_name=file_name)
    elif file_format.lower() == "epub":
        return render_template('main/readepub.html', book_id=book_id, file_name=file_name)


@main.route("/book/<int:book_id>/<file_name>")
@login_required
def get_book(book_id, file_name):
    book = Books.query.get_or_404(book_id)
    file_path = os.path.join(book.path, file_name)
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], file_path)


@main.route("/cover/<int:book_id>")
@login_required
def get_cover(book_id):
    book = Books.query.get_or_404(book_id)
    cover_path = os.path.join(book.path, book.title + '.jpg')
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], cover_path)

app/templates/main/convert_book.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
    <h1>Convert Book</h1>
    <div class="row">
        <div class="col-sm-3 col-lg-2 col-xs-6 book">
            <div class="cover" id="book">
                <a href="{{ url_for('main.read_book', file_format=book.data[0].format.lower(), book_id=book.id) }}">
                    {% if book.has_cover %}
                        <img src="{{ url_for('main.get_cover', book_id=book.id) }}"
                             alt="{{ book.title }}"/>
                    {% else %}
                        <img src="{{ url_for('static', filename='generic_cover.jpg') }}"
                             alt="{{ book.title }}"/>
                    {% endif %}
                </a>
            </div>
            <div class="meta">
                <p class="title">{{ book.title | truncate(15, True) }}</p>
                <p class="author">
                    {% for author in book.authors %}
                        {{ author.name | replace('|',',') }}
                        {% if not loop.last %}
                            &amp;
                        {% endif %}
                    {% endfor %}
                </p>
                {% if book.ratings.__len__() > 0 %}
                    <div class="rating">
                        {% for number in range((book.ratings[0].rating/2)|int(2)) %}
                            <span class="glyphicon glyphicon-star good"></span>
                            {% if loop.last and loop.index < 5 %}
                                {% for numer in range(5 - loop.index) %}
                                    <span class="glyphicon glyphicon-star"></span>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-3 col-lg-2 col-xs-6 book">
            {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
        </div>
    </div>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block page_content %}
    <div class="row">
        {% if books %}
            {% for book in books %}
                <div class="col-sm-3 col-lg-2 col-xs-6 book">
                    <div class="cover">
                        <a href="{{ url_for('main.read_book', file_format=book.data[0].format.lower(), book_id=book.id) }}">
                            {% if book.has_cover %}
                                <img src="{{ url_for('main.get_cover', book_id=book.id) }}"
                                     alt="{{ book.title }}"/>
                            {% else %}
                                <img src="{{ url_for('static', filename='generic_cover.jpg') }}"
                                     alt="{{ book.title }}"/>
                            {% endif %}
                        </a>
                        <div class="delete">
                            <a title="Delete book" class="badge" href="{{ url_for('main.delete_book', book_id=book.id) }}">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </div>
                        <div class="btn-toolbar toolbar" role="toolbar">
                            <a title="Convert book" class="badge" href="{{ url_for('main.convert_book', book_id=book.id) }}">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                            <a title="Send to kindle"  class="badge" href="{{ url_for('main.send_to_kindle', book_id=book.id) }}">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </a>
                        </div>
                    </div>
                    <div>
                        {% for file in book.data %}
                            <a href="{{ url_for('main.read_book', file_format=file.format.lower(), book_id=book.id) }}"
                                   class="badge">{{ file.format.lower() }}</a>
                        {% endfor %}
                    </div>

                    <div class="meta">
                        <p class="title">{{ book.title | truncate(20, True) }}</p>
                        <p class="author">
                            {% for author in book.authors %}
                                {{ author.name | replace('|',',') }}
                                {% if not loop.last %}
                                    &amp;
                                {% endif %}
                            {% endfor %}
                        </p>
                        {% if book.ratings.__len__() > 0 %}
                            <div class="rating">
                                {% for number in range((book.ratings[0].rating/2)|int(2)) %}
                                    <span class="glyphicon glyphicon-star good"></span>
                                    {% if loop.last and loop.index < 5 %}
                                        {% for numer in range(5 - loop.index) %}
                                            <span class="glyphicon glyphicon-star"></span>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2>No Results</h2>
        {% endif %}
    </div>
{% endblock %}

app/templates/main/readepub.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/normalize.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/popup.css') }}">

        <script src="{{ url_for('static', filename='js/libs/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/libs/zip.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/libs/jszip.min.js') }}"></script>

        <script>
            "use strict";

            document.onreadystatechange = function () {
                if (document.readyState == "complete") {
                    window.reader = ePubReader("{{ url_for('main.get_book', book_id=book_id, file_name=file_name) }}", {
                        restore: true
                    });
                }
            };

        </script>

        <!-- File Storage -->
        <!-- <script src="js/libs/localforage.min.js"></script> -->

        <!-- Full Screen -->
        <script src="{{ url_for('static', filename='js/libs/screenfull.min.js') }}"></script>

        <!-- Render -->
        <script src="{{ url_for('static', filename='js/libs/epub.js') }}"></script>

        <!-- Reader -->
        <script src="{{ url_for('static', filename='js/reader.js') }}"></script>

        <!-- Plugins -->
        <!-- <script src="js/plugins/search.js"></script> -->

        <!-- Highlights -->
        <!-- <script src="js/libs/jquery.highlight.js"></script> -->
        <!-- <script src="js/hooks/extensions/highlight.js"></script> -->

    </head>
    <body>
    <div id="sidebar">
        <div id="panels">
            <!-- <input id="searchBox" placeholder="search" type="search"> -->
            <!-- <a id="show-Search" class="show_view icon-search" data-view="Search">Search</a> -->
            <a id="show-Toc" class="show_view icon-list-1 active" data-view="Toc">TOC</a>
            <a id="show-Bookmarks" class="show_view icon-bookmark" data-view="Bookmarks">Bookmarks</a>
            <!-- <a id="show-Notes" class="show_view icon-edit" data-view="Notes">Notes</a> -->
        </div>
        <div id="tocView" class="view">
        </div>
        <div id="searchView" class="view">
            <ul id="searchResults"></ul>
        </div>
        <div id="bookmarksView" class="view">
            <ul id="bookmarks"></ul>
        </div>
        <div id="notesView" class="view">
            <div id="new-note">
                <textarea id="note-text"></textarea>
                <button id="note-anchor">Anchor</button>
            </div>
            <ol id="notes"></ol>
        </div>
    </div>

    <div id="main">
        <div id="titlebar">
            <div id="opener">
                <a id="slider" class="icon-menu">Menu</a>
            </div>
            <div id="metainfo">
                <span id="book-title"></span>
                <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
                <span id="chapter-title"></span>
            </div>
            <div id="title-controls">
                <a id="bookmark" class="icon-bookmark-empty">Bookmark</a>
                <a id="setting" class="icon-cog">Settings</a>
                <a id="fullscreen" class="icon-resize-full">Fullscreen</a>
                <a id="cancel" class="icon-cancel-circled">Exit</a>
            </div>
        </div>

        <div id="divider"></div>
        <div id="prev" class="arrow">‹</div>
        <div id="viewer"></div>
        <div id="next" class="arrow">›</div>
        <div id="loader"><img src="{{ url_for('static', filename='img/loader.gif') }}"></div>
    </div>

    <div class="modal md-effect-1" id="settings-modal">
        <div class="md-content">
            <h3>Settings</h3>
            <div>
                <p>
                    <input type="checkbox" id="sidebarReflow" name="sidebarReflow">Reflow text when sidebars are open.
                </p>
            </div>
            <div class="closer icon-cancel-circled"></div>
        </div>
    </div>
    <div class="overlay"></div>
    </body>
    <script type="text/javascript">
        $("#cancel").on("click", function () {
            self.location = "{{ url_for('main.index') }}";
        });
    </script>
</html>

app/templates/main/readtxt.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{{ title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <meta name="apple-mobile-web-app-capable" content="yes">


        <!-- EPUBJS Renderer -->
        <!--<script src="../build/epub.js"></script>-->
        <script src="{{ url_for('static', filename='js/libs/jquery.min.js') }}"></script>

        <style type="text/css">

          body {
            overflow: hidden;
          }

          #main {
            position: absolute;
            width: 100%;
            height: 100%;
          }

          #area {
            width: 80%;
            height: 80%;
            margin: 5% auto;
            max-width: 1250px;
          }

          #area iframe {
            border: none;
          }

          #prev {
            left: 40px;
          }

          #next {
            right: 40px;
          }

          .arrow {
            position: absolute;
            top: 50%;
            margin-top: -32px;
            font-size: 64px;
            color: #E2E2E2;
            font-family: arial, sans-serif;
            font-weight: bold;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }

          .arrow:hover {
            color: #777;
          }

          .exit {
            position: absolute;
            top: 50px;
            right: 30px;
            margin-top: -32px;
            font-size: 18px;
            color: #E2E2E2;
            font-family: arial, sans-serif;
            font-weight: bold;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
            text-decoration:none;
          }

          .exit:hover {
            color: #777;
          }

          .arrow:active {
            color: #000;
          }
          xmp, pre, plaintext {
            display: block;
            font-family: -moz-fixed;
            white-space: pre;
            margin: 1em 0;
          }
          #area{
            overflow:hidden;
          }
          pre {
            white-space: pre-wrap;
            word-wrap: break-word;
            font-family: -moz-fixed;
            column-count:2;
            -webkit-columns:2;
            -moz-columns:2;
            column-gap:20px;
            -moz-column-gap:20px;
            -webkit-column-gap:20px;
            position:relative;
          }
        </style>
    </head>
    <body>
        <div id="main">
          <div id="prev" class="arrow" >‹</div>
          <div id="area"><pre id="content" class="content"></pre></div>
          <div id="next" class="arrow">›</div>
          <a href="{{ url_for('main.index') }}" class="exit">Exit</a>
        </div>

        <script>

        $(document).ready(function() {
          //to int
          $("#area").width($("#area").width());
          $("#content").width($("#content").width());
          //bind text
          $("#content").load("{{ url_for('main.get_book', book_id=book_id, file_name=file_name) }}",function(textStr) {
           $(this).height($(this).parent().height()*0.95);
           $(this).text(textStr);
          });
          //keybind
          $(document).keydown(function(event){ 
            if(event.keyCode == 37){
              prevPage();
            }
            if(event.keyCode == 39){
              nextPage();
            }
          });
          //click
          $( "#prev" ).click(function() {
            prevPage();
          });
          $( "#next" ).click(function() {
            nextPage();
          });
          //bind mouse
          $(window).bind('DOMMouseScroll mousewheel', function(event) {
            var delta = 0;
            if (event.originalEvent.wheelDelta) {
              delta = event.originalEvent.wheelDelta;
            }else if (event.originalEvent.detail) {
              delta = event.originalEvent.detail*-1;
            }
            if (delta >= 0) {
                  prevPage();
              }
              else {
                  nextPage();
              }
          });
          //page animate
          var origwidth = $("#content")[0].getBoundingClientRect().width;
          var gap = 20;
          function prevPage(){
            if($("#content").offset().left > 0){ return;}
            leftoff = $("#content").offset().left;
            leftoff = leftoff+origwidth+gap;
            $("#content").offset({left:leftoff});
          }
          function nextPage(){
            leftoff = $("#content").offset().left;
            leftoff = leftoff-origwidth-gap;
            $("#content").offset({left:leftoff});
          }
        });

        </script>
    </body>
</html>